---
title: "dauerProtocol3_processingP2"
author: "Corinne Croslyn"
date: "5/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(EMCluster)
library(forcats)

# set working directory
setwd(glue::glue("{dirname(rstudioapi::getActiveDocumentContext()$path)}/.."))
```

Ok, using Daehan's data to train clustering for our own didn't work well. Let's try a different approach, using only our own data this time.

## Part 1: process sorter data 

```{r}
# Define a vector of your experiment directories. Can load more
dirs <- c("data/raw/20220427_dauerProtocol3") 

# Read in the data using easysorter: https://github.com/AndersenLab/easysorter
raw <- easysorter::read_data(dirs)

# look at score data for each color channel
score_proc <- as.data.frame(raw[1]) %>%
  dplyr::filter(call50 != "bubble", contamination != "TRUE", !is.na(strain)) %>%
  dplyr::mutate(well = paste(plate,row,col, sep = ""))
```

## Part 2: Using our controls to train clustering of our data 

### Getting classes from our own (green) data

```{r}
raw_dauers <- easysorter::read_data("data/raw/20220427_dauerProtocol3") # FOR NOW USE THIS ASSAY FOR SETTINGS

proc_dauers <- as.data.frame(raw_dauers[1]) %>%
  dplyr::mutate(well = paste(plate,row,col, sep = ""))

# EM clustering in DI condition
df_raw <- proc_dauers %>%
  dplyr::filter(!is.na(strain)) %>%
  #dplyr::filter(strain %in% c("JU346", "ECA1089", "ECA1119", "ECA1121", "NIC166", "ECA1091", "ECA1120", "ECA1122")) %>%
  dplyr::filter(condition %in% c("control_4hr", "20uM_ascr5_4hr", "10uM_ascr5_4hr"))
  #dplyr::filter(TOF>100)

df_green <- df_raw[c("TOF", "green", "EXT")]
ret.em_K4_green <- EMCluster::init.EM(df_green, nclass = 8, method = "em.EM")
green_merge_K4 <- data.frame(df_raw, ret.em_K4_green[6])

# plot to define classes
ggplot(green_merge_K4) +
  aes(x = TOF, y = green, scale = T, color = as.factor(class)) +
  geom_point(size=1, alpha = 0.3)+
  theme(text = element_text(size=12),
        axis.text.x = element_text(angle=45, hjust=1)) +
  labs(title = "Dauer Assay 3 20uM ascr5 + Control, 4hr (green)") +
  theme_bw() + 
  ylim(0, 300) +
  xlim(0, 600)
```

```{r}
# Caution!!! factor label changes everytime!!!
green_merge_K4$class <- factor(green_merge_K4$class, levels=c(1,4,2,3,5,6), labels=c("dauer1","dauer2", "non-dauer1", "non-dauer2", "other1", "other2"))

green_merge_K4$class <- fct_collapse(green_merge_K4$class, dauer = c("dauer1","dauer2"), nondauer = c("non-dauer1", "non-dauer2"), other = c("other1","other2"))

# replot with new factor names
ours_plot_green <- green_merge_K4 %>%
  #dplyr::filter(!is.na(strain)) %>%
  #dplyr::filter(class %in% c("dauer", "non-dauer")) %>%
  ggplot(.) +
  aes(x = TOF, y = green, scale = T, color = as.factor(class)) +
  geom_point(size=1, alpha = 0.3) +
  theme(text = element_text(size=12),
        axis.text.x = element_text(angle=45, hjust=1)) +
  facet_grid(~condition) +
  labs(title = "Dauer Assay 3 20uM ascr5 + 10 uM ascr5 + Control, 4hr (green)", color = "") +
  theme_bw() +
 #ylim(0, 300) +
  xlim(0, 600)

ours_plot_green

cowplot::ggsave2(ours_plot_green, filename = "plots/our_green_classes.png", width =5, height = 5)
```

### Using our classes (defined from our own data) to apply to the rest of our data

```{r}
# applying model from DI condition to all our data
ours_g <- score_proc[c("TOF","green", "EXT")]
ret.em_K4_ours_g2 <- EMCluster::assign.class(ours_g, ret.em_K4_green) 
y_merge_K4_ours_g2 <- data.frame(score_proc, ret.em_K4_ours_g2[6])

# CHANGES EVERY TIME! (same as defined above)
y_merge_K4_ours_g2$class <- factor(y_merge_K4_ours_g2$class, levels=c(1,4,2,3,5,6), labels=c("dauer1","dauer2", "non-dauer1", "non-dauer2", "other1", "other2"))

y_merge_K4_ours_g2$class <- fct_collapse(y_merge_K4_ours_g2$class, dauer = c("dauer1","dauer2"), nondauer = c("non-dauer1", "non-dauer2"), other = c("other1","other2"))

# plot to define classes
dauer_assay3_green <- ggplot(y_merge_K4_ours_g2) +
  aes(x = TOF, y = green, scale = T, color = as.factor(class)) +
  #scale_color_manual(values = ) # can use to set colors consistently
  geom_point(size=1, alpha = 0.3)+
  theme(text = element_text(size=12),
        axis.text.x = element_text(angle=45, hjust=1)) +
  labs(title = "Dauer Assay 3 Classes (Green Channel)", color = "") +
  facet_wrap(~condition) +
  theme_bw() +
  ylim(0, 300) +
  xlim(0, 600)

dauer_assay3_green

cowplot::ggsave2(dauer_assay3_green, filename = "plots/dauer_assay3_clusters_by_condition_green.png", width = 5, height = 5)
```

